numpy와 닮은 파이토치

In [8]:
import torch
a = torch.tensor([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype) # int64
print(a.shape)
b = torch.tensor([1, 2, 3.1, 4])
print(b.dtype) # float32

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32


In [14]:
A = torch.tensor([[1, 2],
                  [3, 4]])
'''B = torch.tensor([[1, 2],
                  [3, 4, 5]]) # 에러 발생
                  '''
print(A)
print(A.shape)
print(A.size())
print(A.ndim)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.Size([2, 2])
2


In [15]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(A)
print(A.shape)
print(A.ndim)
print(A.numel())

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
2
6


In [26]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.ones_like(A))
print(torch.arange(3, 10, 2)) # 간격이 2, end 미만
print(torch.reshape(A, (3, 2)))
print(torch.linspace(0, 1, 10)) # 개수가 10, 포함

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([3, 5, 7, 9])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [38]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
B = torch.tensor([[7, 8, 9],
                 [10, 11, 12]])
print(A + B)
print(A - B)
print(A * B)
print(A / B)
print(B // A)
print(A @ B.t())
print(A.mul_(B))
print(A.matmul(B.t()))
print(A)
print(B)
print(B.pow(2))
print(B.pow_(2))
print(B)


tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])
tensor([[7, 4, 3],
        [2, 2, 2]])
tensor([[ 50,  68],
        [122, 167]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 420,  570],
        [1368, 1869]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 49,  64,  81],
        [100, 121, 144]])
tensor([[ 49,  64,  81],
        [100, 121, 144]])
tensor([[ 49,  64,  81],
        [100, 121, 144]])


In [45]:
a = torch.arange(1, 10, 1)
print(a)
print(a[0])
print(a[1:8])
b = torch.reshape(a, (3, 3))
print(b)
print(b[0])
print(b[0, 2])
print(b[0][2])

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(1)
tensor([2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(3)
tensor(3)
